#version: v2.1.8.{build}
os:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - Win64

install:
  - cmd: echo %CI%

build_script:
  - ps: Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-Webrequest "https://raw.githubusercontent.com/xmake-io/xmake/dev/scripts/get.ps1" -UseBasicParsing).Content)) -ArgumentList "dev"
  - cmd: xmake lua versioninfo
  - cmd: xmake -P core 
  - cmd: set XMAKE_PROGRAM_DIR=%cd%\xmake
  - cmd: core\build\xmake lua versioninfo
  - ps: Copy-Item -Force core\build\xmake.exe $HOME\xmake
  - cmd: xmake lua -D tests\test.lua

#on_success:
#  - ps: $env:XMAKE_PROGRAM_DIR=$null
#  - ps: Invoke-Expression (Get-Content scripts\getpb.ps1 | Out-String)

after_build:
  - ps: Copy-Item core\build\xmake.exe .

artifacts:
  - path: xmake.exe
