sudo: false
language: C
os:
  - linux
  - osx

script:
  - scripts/get.sh __local__
  - xmake lua versioninfo
  - xmake -P core
  - $(cat $(which xmake)|grep XMAKE_PROGRAM_DIR)
  - core/build/xmake lua versioninfo
