sudo: required
language: C
os:
  - linux
  - osx

install:
  - cd ..
  - cp -r xmake xmake4build
  - cd xmake4build
  - make build; sudo make install
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update --verbose; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install dmd --verbose; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install rust --verbose; fi

script:
  - cd ../xmake/core
  - xmake -v
  - sudo cp -v build/xmake /usr/local/share/xmake
  - xmake --version
  - xmake create test_project
  - cd test_project
  - xmake
