sudo: required
language: C
os:
  - linux
  - osx

install:
  - cd ..
  - cp -r xmake xmake4build
  - cd xmake4build
  - sudo ./install
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update --verbose; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install dmd --verbose; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install rust --verbose; fi

script:
  - cd ../xmake/core
  - xmake -v
