os: Visual Studio 2015

platform:
  - Win32
  - Win64

before_build:
  - ps: Invoke-WebRequest "https://github.com/tboox/xmake/releases/download/v2.1.2/xmake-v2.1.2.exe" -OutFile "xmake-installer.exe"
  - cmd: xmake-installer.exe /S /D=C:\xmake
  - cmd: PATH=%PATH%;C:\xmake
  - cmd: xmake --version
  - ps: cp -r -force xmake\* C:\xmake
  - cmd: xmake --version
  - cmd: dir C:\xmake

build_script:
  - cmd: cd core
  - cmd: if %platform%==Win64 xmake f -a x64
  - cmd: xmake -v
