version: v2.1.5.{build}
os:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - Win64

install:
  - ps: Invoke-Webrequest 'http://luarocks.github.io/luarocks/releases/luarocks-2.4.2-win32.zip' -OutFile luarocks.zip
  - ps: Expand-Archive luarocks.zip
  - ps: Copy-Item -Recurse luarocks\luarocks-2.4.2-win32\win32\lua5.1 C:\lua
  - cmd: cd luarocks\luarocks-2.4.2-win32
  - cmd: install.bat /Q
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\LuaRocks
  - cmd: cd ..\..
  - ps: Remove-Item luarocks -Recurse -Force
  - ps: Remove-Item luarocks.zip
  - cmd: luarocks install luacov

build_script:
  - ps: Invoke-Expression (Get-Content scripts\get.ps1 | Out-String)
  - cmd: xmake lua versioninfo
  - cmd: if %platform%==Win64 xmake f -a x64 -P core
  - cmd: xmake -P core
  - cmd: set XMAKE_PROGRAM_DIR=%cd%\xmake
  - cmd: core\build\xmake lua versioninfo
